# Generated by Django 4.2.9 on 2024-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('Mobile_number1', models.CharField(max_length=255)),
                ('Mobile_number12', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('ig', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('snapchat', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
            ],
        ),
    ]
