# Generated by Django 4.2.9 on 2024-01-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile_number1',
            new_name='mobile_number1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile_number12',
            new_name='mobile_number2',
        )
    ]
