# Generated by Django 4.2.9 on 2024-01-14 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('mobile_number1', models.CharField(max_length=255)),
                ('mobile_number2', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('ig', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('snapchat', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
